! leaf1 - AS 65011 - VTEP 10.0.0.11
!
frr defaults datacenter
hostname leaf1
log stdout
!
ip forwarding
ipv6 forwarding
!
vrf tenant-A
 vni 5000
exit-vrf
!
vrf tenant-B
 vni 5001
exit-vrf
!
interface lo
 ip address 10.0.0.11/32
!
interface eth1
 description to-spine1
 no shutdown
!
interface eth2
 description to-spine2
 no shutdown
!
! ---------- BGP underlay + overlay EVPN ----------
router bgp 65011
 bgp router-id 10.0.0.11
 bgp bestpath as-path multipath-relax
 no bgp default ipv4-unicast
 neighbor FABRIC peer-group
 neighbor FABRIC remote-as external
 neighbor FABRIC capability extended-nexthop
 neighbor FABRIC bfd profile FABRIC
 neighbor FABRIC ttl-security hops 1
 neighbor FABRIC advertisement-interval 0
 neighbor FABRIC timers 3 9
 neighbor FABRIC timers connect 5
 neighbor eth1 interface peer-group FABRIC
 neighbor eth2 interface peer-group FABRIC
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor FABRIC activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC maximum-prefix 5000
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
!
! ---------- VRF tenant-A: Type-5 + anycast GW ----------
router bgp 65011 vrf tenant-A
 bgp router-id 10.0.0.11
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
 exit-address-family
!
! ---------- VRF tenant-B ----------
router bgp 65011 vrf tenant-B
 bgp router-id 10.0.0.11
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
 exit-address-family
!
bfd
 profile FABRIC
  transmit-interval 150
  receive-interval 150
  detect-multiplier 3
 exit
exit
!
end
